---
- hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: testA-rg
        location: westeurope
      register: rg
    - debug:
        var: rg
