#
#
#   docker container run -dit -p 8080:5000
#--ulimit nofile=1024 --tmpfs /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
# -v monitoring:/omd/sites --name monitoring -v /etc/localtime:/etc/localtime:ro
# --restart always checkmk/check-mk-raw:1.6.0-latest
#
