name: AzureAD

on:
  push:
    branches: 
    - master

jobs:
  pstest:
    name: Test PowerShell scripts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Pester module
      run: Install-Module Pester -Force
      shell: pwsh
      
    - name: Run Pester
      run: Invoke-Pester AzureAD/.
      shell: pwsh

