name: AzureAD

on:
  push:
    branches: 
    - master

jobs:
  pstest:
    name: Test PowerShell scripts
    runs-on: ubuntu-latest

    steps:
    - id: step1
      name: Pull the source code.
      uses: actions/checkout@v2

    - name: Install Static Code analysis module
      run: Install-Module PSScriptAnalyzer -Force
      shell: pwsh

    - name: Static Code analysis
      run: Invoke-ScriptAnalyzer -Path AzureAD/ -ReportSummary -EnableExit
      shell: pwsh

    #- name: Install Microsoft Graph module
    #  run: Install-Module Microsoft.Graph -Force -ErrorAction SilentlyContinue
    #  shell: pwsh

    - name: Install Pester module
      run: Install-Module Pester -Force
      shell: pwsh
    #  if: ${{ success() || failure() }}

    - name: Unit tests analysis
      run: Invoke-Pester -EnableExit -Script AzureAD/
      shell: pwsh

