name: AzureAD

on:
  push:
    branches: 
    - master

jobs:
  pstest:
    name: Test PowerShell scripts
    runs-on: ubuntu-latest

    steps:
    - name: Pull the source code.
      uses: actions/checkout@v2

    - name: Install Pester module
      run: Install-Module Pester -Force
      shell: pwsh

    - name: Static Code analysis
      run: Invoke-ScriptAnalyzer -Path AzureAD/ -ReportSummary -EnableExit
      shell: pwsh

    - name: Unit tests analysis
      run: Invoke-Pester -EnableExit -Script AzureAD/
      shell: pwsh

