name: Docker Image CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    name: Test PowerShell in docker
    runs-on: ubuntu-latest

    steps:
    - name: Display date and time
      run: Get-Date
      shell: pwsh
    - name: Get current location for Powershell
      run: Get-Location
      shell: pwsh
    - name: Get location bash
      run: ls
    #- name: Build the Docker image
      #run: docker-compose run --rm azuread
      #run: docker build --file ./AzureAD/Dockerfile #-t azuread/pester-runner 
      #run: docker build . --file AzureAD/Dockerfile --tag test-azuread:$(date +%s)
    - name: Install Pester
      run: Install-Module Pester -Force
      shell: pwsh
      #run: docker run -it --rm -v ${pwd}:/test azuread/pester-runner
