name: Docker Image CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    name: Test PowerShell in docker
    runs-on: ubuntu-latest

    steps:
    - name: Display the path
      run: echo ${pws}
      shell: pwsh
    - name: Build the Docker image
      run: docker build -t azuread/pester-runner --file ./AzureAD/Dockerfile
      #run: docker build . --file AzureAD/Dockerfile --tag test-azuread:$(date +%s)
    - name: Run tests in the Docker image
      run: docker run -it --rm -v ${pwd}:/test azuread/pester-runner
